packages:
  - packages/*
  - benchmarks/*
  - examples/*

allowBuilds:
  esbuild: true
  fallow: true
  protobufjs: true

catalog:
  '@emnapi/core': 2.0.0-alpha.3
  '@emnapi/runtime': 2.0.0-alpha.3
  '@napi-rs/cli': 3.8.0
  '@napi-rs/wasm-runtime': 1.2.1
  '@types/node': 26.1.2
  'nanoid': 6.0.0
  '@faker-js/faker': 10.5.0
  '@opentelemetry/api': 1.9.0
  '@opentelemetry/context-async-hooks': 2.5.1
  '@opentelemetry/core': 2.5.1
  '@opentelemetry/semantic-conventions': 1.38.0
  '@opentelemetry/resources': 1.30.1
  '@opentelemetry/sdk-metrics': 1.30.1
  '@opentelemetry/sdk-trace-base': 1.30.1
  '@opentelemetry/sdk-trace-node': 1.30.1
  '@opentelemetry/exporter-metrics-otlp-grpc': 0.57.2
  '@opentelemetry/exporter-trace-otlp-grpc': 0.57.2
  '@opentelemetry/sdk-node': 0.57.2

overrides:
  emnapi: 2.0.0-alpha.3

supportedArchitectures:
  cpu:
    - current
    - wasm32

onlyBuiltDependencies:
  - '@platformatic/rdkafka'
  - dprint
  - esbuild
  - protobufjs

minimumReleaseAgeExclude:
  - '@napi-rs/wasm-runtime@1.2.1'
