import { configurePdfRuntime, createPdf, createPdfAsync, PdfDocument } from './api.js'

// @ts-expect-error The WASI browser binding is generated by the NAPI build.
const binding = await import(/* @vite-ignore */ '../pdf-crab-js.wasi-browser.js')

configurePdfRuntime({
  binding: binding as never,
  resolveImageSource(source) {
    if (typeof source === 'string') {
      throw new TypeError(
        'image file paths are only supported in the Node.js entrypoint; pass Uint8Array or ArrayBuffer',
      )
    }
    if (source instanceof ArrayBuffer) return new Uint8Array(source)
    return new Uint8Array(source.buffer, source.byteOffset, source.byteLength)
  },
})

export { PdfDocument, createPdf, createPdfAsync }
export type {
  CreatePdfInput,
  PdfAnnotationInput,
  PdfDocumentOptions,
  PdfElementInput,
  PdfImageAlign,
  PdfImageBytes,
  PdfImageElement,
  PdfImageOptions,
  PdfImageSource,
  PdfImageValign,
  PdfLayout,
  PdfLineElement,
  PdfLinkOptions,
  PdfMargins,
  PdfMetadata,
  PdfPageInput,
  PdfPageOptions,
  PdfPageSize,
  PdfPathElement,
  PdfPolygonElement,
  PdfRectElement,
  PdfStyleOptions,
  PdfTextAlign,
  PdfTextBoxElement,
  PdfTextBoxOptions,
  PdfTextElement,
  PdfTextOptions,
  PdfUnit,
} from './api.js'
