import { configurePdfRuntime } from './api.js'
import { Buffer as BrowserBuffer } from 'buffer'

globalThis.Buffer ??= BrowserBuffer

// @ts-expect-error The WASI browser binding is generated by the NAPI build.
const binding = await import(/* @vite-ignore */ '../pdf-crab-js.wasip1-browser.js')

configurePdfRuntime({
  binding: binding as never,
  resolveImageSource(source) {
    if (typeof source === 'string') {
      throw new TypeError(
        'image file paths are only supported in the Node.js entrypoint; pass Uint8Array or ArrayBuffer',
      )
    }
    if (source instanceof ArrayBuffer) return new Uint8Array(source)
    return new Uint8Array(source.buffer, source.byteOffset, source.byteLength)
  },
})

export { PdfDocument, PdfError, renderPdf } from './api.js'
export type {
  PdfDocumentInput,
  PdfAnnotationInput,
  PdfDocumentOptions,
  PdfElementInput,
  PdfImageAlign,
  PdfImageBytes,
  PdfImageElement,
  PdfImageOptions,
  PdfImageSource,
  PdfImageValign,
  PdfLayout,
  PdfLineElement,
  PdfLinkOptions,
  PdfMargins,
  PdfMetadata,
  PdfPageInput,
  PdfPageOptions,
  PdfPageSize,
  PdfPolylineElement,
  PdfPolygonElement,
  PdfRectElement,
  PdfStrokeStyleOptions,
  PdfFillStyleOptions,
  PdfFontRegistrationOptions,
  PdfFontInput,
  PdfFontSource,
  PdfTextStyleOptions,
  PdfTableCellStyle,
  PdfTableCellValue,
  PdfTableColumn,
  PdfTableColumnWidth,
  PdfTableOptions,
  PdfOutput,
  PdfOutputOptions,
  PdfErrorCode,
  PdfStreamOptions,
  PdfTextAlign,
  PdfTextBoxOptions,
  PdfTextElement,
  PdfTextOptions,
  PdfTextOverflow,
  PdfUnit,
} from './api.js'
