import { mkdirSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import { PdfDocument } from 'pdf-crab-js'

const exampleDirectory = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..')
const outputDirectory = path.join(exampleDirectory, 'output')
const outputPath = path.join(outputDirectory, 'pdf-crab-js-table-example.pdf')

type TableRow = {
  id: string
  customer: string
  region: string
  status: string
  amount: string
  owner: string
}

const rows: TableRow[] = [
  { amount: '1,240.00', customer: 'Acme North', id: '000001', owner: 'team-a', region: 'LATAM', status: 'paid' },
  { amount: '2,870.50', customer: 'Beacon Labs', id: '000002', owner: 'team-b', region: 'NA', status: 'pending' },
  { amount: '940.20', customer: 'Crimson Works', id: '000003', owner: 'team-c', region: 'EMEA', status: 'paid' },
  { amount: '4,210.90', customer: 'Delta One', id: '000004', owner: 'team-d', region: 'APAC', status: 'overdue' },
  { amount: '1,780.35', customer: 'Evergreen Co', id: '000005', owner: 'team-a', region: 'LATAM', status: 'refunded' },
  { amount: '3,540.00', customer: 'Northstar', id: '000006', owner: 'team-b', region: 'NA', status: 'paid' },
]

const document = new PdfDocument({
  title: 'pdf-crab-js table example',
  unit: 'mm',
  size: 'A4',
  margin: 18,
})

document
  .font('HelveticaBold')
  .fontSize(18)
  .text('Revenue Table')
  .font('Helvetica')
  .fontSize(9)
  .fillColor('#475569')
  .text('Typed columns, automatic borders, alternating rows, and repeated headers.')
  .table({
    columns: [
      { key: 'id', header: 'ID', width: 18 },
      { key: 'customer', header: 'Customer', width: '*' },
      { key: 'region', header: 'Region', width: 26 },
      { key: 'status', header: 'Status', width: 31 },
      { key: 'amount', header: 'Amount', width: 28, align: 'right' },
      { key: 'owner', header: 'Owner', width: 27 },
    ],
    rows,
    stripe: '#f8fafc',
    border: '#cbd5e1',
    padding: 3,
    repeatHeader: true,
  })
  .fontSize(8)
  .fillColor('#64748b')
  .text('Generated by pdf-crab-js 1.0')

mkdirSync(outputDirectory, { recursive: true })
const pdf = await document.render().bytes()
writeFileSync(outputPath, pdf)

console.log(`Generated ${outputPath}`)
console.log(`Size: ${pdf.byteLength.toLocaleString()} bytes`)
