import { mkdirSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import { PdfDocument } from 'pdf-crab-js'

const currentDirectory = path.dirname(fileURLToPath(import.meta.url))
const outputDirectory = path.join(currentDirectory, 'output')
const outputPath = path.join(outputDirectory, 'pdf-crab-js-table-example.pdf')

const tableX = 18
const tableTopY = 60
const tableWidth = 174
const headerHeight = 11
const rowHeight = 12
const cellPaddingX = 3

const columns = [
  { key: 'id', label: 'ID', width: 18 },
  { key: 'customer', label: 'Customer', width: 44 },
  { key: 'region', label: 'Region', width: 26 },
  { key: 'status', label: 'Status', width: 31 },
  { key: 'amount', label: 'Amount', width: 28 },
  { key: 'owner', label: 'Owner', width: 27 },
] as const

type ColumnKey = (typeof columns)[number]['key']
type TableRow = Record<ColumnKey, string>

const rows: TableRow[] = [
  { amount: '1,240.00', customer: 'Acme North', id: '000001', owner: 'team-a', region: 'LATAM', status: 'paid' },
  { amount: '2,870.50', customer: 'Beacon Labs', id: '000002', owner: 'team-b', region: 'NA', status: 'pending' },
  { amount: '940.20', customer: 'Crimson Works', id: '000003', owner: 'team-c', region: 'EMEA', status: 'paid' },
  { amount: '4,210.90', customer: 'Delta One', id: '000004', owner: 'team-d', region: 'APAC', status: 'overdue' },
  { amount: '1,780.35', customer: 'Evergreen Co', id: '000005', owner: 'team-a', region: 'LATAM', status: 'refunded' },
  { amount: '3,540.00', customer: 'Northstar', id: '000006', owner: 'team-b', region: 'NA', status: 'paid' },
]

const document = new PdfDocument({
  title: 'pdf-crab-js table example',
  unit: 'mm',
  size: 'A4',
  margin: 18,
})

function line(x1: number, y1: number, x2: number, y2: number, color: string, width: number): void {
  document.strokeColor(color).lineWidth(width).moveTo(x1, y1).lineTo(x2, y2).stroke()
}

function text(
  value: string,
  x: number,
  y: number,
  options: { fill?: string; font?: string; fontSize?: number } = {},
): void {
  document.text(value, {
    x,
    y,
    fill: options.fill ?? '#111827',
    font: options.font,
    fontSize: options.fontSize ?? 8,
  })
}

text('Simple Revenue Table', tableX, 24, { font: 'HelveticaBold', fontSize: 18 })
text('A table built with rectangles, lines, and text in top-left coordinates.', tableX, 36, {
  fill: '#475569',
  fontSize: 9,
})

document
  .fillColor('#e2e8f0')
  .strokeColor('#cbd5e1')
  .lineWidth(0.8)
  .rect(tableX, tableTopY, tableWidth, headerHeight)
  .fillAndStroke()

for (let index = 0; index < rows.length; index += 1) {
  const y = tableTopY + headerHeight + index * rowHeight
  document
    .fillColor(index % 2 === 0 ? '#ffffff' : '#f8fafc')
    .rect(tableX, y, tableWidth, rowHeight)
    .fill()
}

const tableBottomY = tableTopY + headerHeight + rows.length * rowHeight
line(tableX, tableTopY, tableX + tableWidth, tableTopY, '#cbd5e1', 0.8)
line(tableX, tableBottomY, tableX + tableWidth, tableBottomY, '#cbd5e1', 0.8)

for (let index = 1; index <= rows.length; index += 1) {
  const y = tableTopY + headerHeight + index * rowHeight
  line(tableX, y, tableX + tableWidth, y, '#cbd5e1', 0.4)
}

let x = tableX
for (const column of columns) {
  line(x, tableTopY, x, tableBottomY, '#cbd5e1', 0.4)
  x += column.width
}
line(tableX + tableWidth, tableTopY, tableX + tableWidth, tableBottomY, '#cbd5e1', 0.4)

x = tableX
for (const column of columns) {
  text(column.label, x + cellPaddingX, tableTopY + 3, { fill: '#0f172a', font: 'HelveticaBold', fontSize: 7 })
  x += column.width
}

for (const [rowIndex, row] of rows.entries()) {
  x = tableX
  const y = tableTopY + headerHeight + rowIndex * rowHeight + 3.5
  for (const column of columns) {
    text(row[column.key], x + cellPaddingX, y, { fontSize: 7 })
    x += column.width
  }
}

text('Generated by pdf-crab-js 1.0', tableX, tableBottomY + 16, { fill: '#64748b', fontSize: 8 })

const pdf = document.finish()
mkdirSync(outputDirectory, { recursive: true })
writeFileSync(outputPath, pdf)

console.log(`Generated ${outputPath}`)
console.log(`Size: ${pdf.byteLength.toLocaleString()} bytes`)
